### ISSUE TITLE
Improve documenation

### ISSUE THREAD

**Issue by elijahgagne** [gscales/Exch-Rest#1]
Thanks for doing this Glen. If it's OK, I plan to open issues as a way to discuss changes I'd like to propose and get your input before I start working on something. As a bit of a warm up and a way to familiarize myself with all the work you've done, I'd like to work on improving the documentation.

**Comment by gscales** [comment]
Sure sound good, i think one of the hardest things to do at the moment is understand the initial setup of the Azure application registration as compared to EWS where you must could provide credentials and get going. Let me know any questions you need answered.

**Comment by elijahgagne** [comment]
I've made a first pass at things and you can view the updated readme at https://github.com/elijahgagne/Exch-Rest/tree/Issue1. You'll notice that I created a branch for this and issued a pull request. If you agree with these change, I think you'd accept the pull request and then merge the branch into master. Please feel free to change anything I've written if there are improvements you see. If you like what I've done, I can continue adding more example usage and writing descriptions of the functions.

**Comment by gscales** [comment]
Looks good Elijah thanks I've committed that change the only minor change I made was the module is available via the Powershell gallery now as well.

**Comment by elijahgagne** [comment]
Great. I'll go ahead and close this issue. I'll sneak in more updates to the documentation with some code updates.
