### ISSUE TITLE
Problems installing

### ISSUE THREAD

**Issue by robertstrom** [gscales/Exch-Rest#10]
I have tried installing via this method Install-Module Exch-Rest Import-Module Exch-Rest and get the error message

PS C:\windows\system32> Install-Module Exch-Rest Import-Module Exch-Rest
Install-Module : A positional parameter cannot be found that accepts argument 'Import-Module'.
At line:1 char:1
+ Install-Module Exch-Rest Import-Module Exch-Rest
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Install-Module], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Install-Module
 

**I then tried using the script and get this error**

Import-Module : The module manifest 'C:\Users\g051700\Documents\WindowsPowerShell\Modules\Exch-Rest\Exch-Rest.psd1' could not be processed because it is not a valid 
Windows PowerShell restricted language file. Remove the elements that are not permitted by the restricted language:
At C:\Users\g051700\Documents\WindowsPowerShell\Modules\Exch-Rest\Exch-Rest.psd1:22 char:9
+ GUID = 'fa6095ab-c4b8-4919-ae37-d09d00d23bb3'
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected token 'fa6095ab-c4b8-4919-ae37-d09d00d23bb3'
# Author of this module
Author = 'Glen' in expression or statement.
At C:\Users\g051700\Documents\WindowsPowerShell\Modules\Exch-Rest\Exch-Rest.psd1:22 char:9
+ GUID = 'fa6095ab-c4b8-4919-ae37-d09d00d23bb3'
+         ~
The hash literal was incomplete.
At C:\Users\g051700\Documents\WindowsPowerShell\Modules\Exch-Rest\Exch-Rest.psd1:123 char:1
+ }
+ ~
Unexpected token '}' in expression or statement.
At line:21 char:1
+ Import-Module -Name Exch-Rest
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (C:\Users\g05170...\Exch-Rest.psd1:String) [Import-Module], MissingMemberException
    + FullyQualifiedErrorId : Modules_InvalidManifest,Microsoft.PowerShell.Commands.ImportModuleCommand

I have launched the ISE as Administrator. I am running Windows 10 on PS version PSVersion                      5.1.14393.1770 

Any help / suggestions would be greatly appreciated.

Thanks!

**Comment by robertstrom** [comment]
I got it figured out

There was a conflict as per this page - https://til.secretgeek.net/powershell/psget_conflicts_with_PowerShellGet.html

Thanks

**Comment by FriedrichWeinmann** [comment]
Closing, as it has been resolved by the user himself
