### ISSUE TITLE
Get-AccessToken

### ISSUE THREAD

**Issue by AlexSen** [gscales/Exch-Rest#15]
Hi.
Have issue on connecting.
![image](https://user-images.githubusercontent.com/6735288/40980399-96fcbbe4-68d8-11e8-8a09-154b6b54101b.png)

**Comment by gscales** [comment]
Okay thanks there was a bug in one of the branches that was still calling some old code I've checked in a change to the repository to fix this and updated the version on the powershell gallery to 3.9 with this fix
