### ISSUE TITLE
Auth step

### ISSUE THREAD

**Issue by AlexSen** [gscales/Exch-Rest#16]
Hi again :)
When connecting to mailbox using Registered App with redirect UTI = "urn:ietf:wg:oauth:2.0:oob", auth doesn't work.
Just opens a blank browser window and no result. Here is videoshot
https://www.youtube.com/watch?v=JRkw1ah0JWM

**Comment by gscales** [comment]
Can you try using the parameter -Prompt login in Connect-EXRMailbox that should force a new login rather then presenting the box to choose an existing one. It looks like that process in causing it  redirecting somewhere else when that is happening. You could use fiddler to work out what its trying to redirect to (and that let you also see fully what its trying to do) but using the login prompt should fix it.

**Comment by gscales** [comment]
no feedback
