### ISSUE TITLE
Authentication with Certificate error

### ISSUE THREAD

**Issue by Narzard** [gscales/Exch-Rest#22]
Hi I am connecting to a mailbox using:

```
PS C:\> Connect-EXRMailbox -MailboxName willy@wonka.com -certificateFileName "C:\temp\cert.cer" -clientId "c637e71c-ceb1-4dde-8e3a-
xxxxxxxxx"
```

When it prompts me for password, I get this:

```
PS C:\> Connect-EXRMailbox -MailboxName willy@wonka.com -certificateFileName "C:\temp\cert.cer" -clientId "c637e71c-ceb1-4dde-8e3a-
xxxxxxxxx"
Enter password for certificate file: ***********
Exception calling "CreateSignature" with "1" argument(s): "No asymmetric key object has been associated with this formatter object."
At line:68 char:3
+         $sig = [System.Convert]::ToBase64String($sigform.CreateSignat ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : CryptographicUnexpectedOperationException

Cached Token for graph.microsoft.com xxxxxxxxxxxx.onmicrosoft.com
Error getting Access Token
At line:144 char:21
+                     throw "Error getting Access Token"
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error getting Access Token:String) [], RuntimeException
    + FullyQualifiedErrorId : Error getting Access Token
```

Any Idea why the built in module is not converting the password correctly?

**Comment by gscales** [comment]
I've seen that error before and it has to do with the way the certificate is created from memory the important switch to use is the provider must be 'Microsoft Enhanced RSA and AES Cryptographic Provider' the default and other providers don't work

**Comment by Narzard** [comment]
I will give that a shot and report back tomorrow. Thank you for the quick response.

**Comment by Narzard** [comment]
I was able to recreate the certificate using your linked documentation in AuthenticationMethods.md and the script was here: https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azuread . I changed the Provider line to be Microsoft Enhanced RSA and AES Cryptographic Provider .

Unfortunately, I still get 

```
PS C:\> Connect-EXRMailbox -MailboxName xxx@xxx.onmicrosoft.com -certificateFileName "C:\temp\Azure2.cer" -clientId "c637e71c-ceb1-4dde-8e3a
-e923exxxxx"
Enter password for certificate file: ***********
Exception calling "CreateSignature" with "1" argument(s): "No asymmetric key object has been associated with this formatter object."
At line:68 char:3
+         $sig = [System.Convert]::ToBase64String($sigform.CreateSignat ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : CryptographicUnexpectedOperationException

Cached Token for graph.microsoft.com group.onmicrosoft.com
Error getting Access Token
At line:144 char:21
+                     throw "Error getting Access Token"
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error getting Access Token:String) [], RuntimeException
    + FullyQualifiedErrorId : Error getting Access Token
```

Any ideas?

**Comment by gscales** [comment]
Okay I was able to repro the issue, so one problem is I've hard coded the provider to "Microsoft Enhanced RSA and AES Cryptographic Provider" so if you have fixed that in the generation script you should be able to use the pfx file instead of the cer (as that won't contain the private key necessary for the signature). When i used the pfx file it worked with a certificate generated from that  script.

**Comment by gscales** [comment]
The other option is to generate the certificate with Invoke-EXRCreateSelfSignedCert

**Comment by Narzard** [comment]
That worked. Thanks! Key was definitely to use the .pfx and not the .cer
