### ISSUE TITLE
Id must be non-empty error when running New-EXRContact

### ISSUE THREAD

**Issue by fmdefranca** [gscales/Exch-Rest#28]
Getting the below error message when trying to add a new contact into use mailbox.

This is the command i used and got the below error:
New-EXRContact -MailboxName user@contoso.com -FirstName "FirstName" -LastName "Surname of Contact" -EmailAddress "EmailAddress@domain.com" -MobilePhone 1111-222-333

{"error":{"code":"ErrorInvalidIdEmpty","message":"Id must be non-empty."}}

This is the requestURL that i get which i can see contactFolders is empty? not sure if this is the cause.
https://graph.microsoft.com/v1.0/users('user@contoso.com')/contactFolders('')/Contacts/

Thanks

**Comment by gscales** [comment]
This was a bug it should be fixed in the new version on the Gallery 3.49.0
