### ISSUE TITLE
Applying retention policy to folder:

### ISSUE THREAD

**Issue by michaelblanchard64** [gscales/Exch-Rest#29]
Applying a retentionpolicy to folder with this command:
Set-EXRFolderRetentionTag -RetentionFlagsValue 137 -retentionperiodvalue 0  -PolicyTagValue  '414C6A14-3ED5-432E-9EDB-C6620A8278F0' -FolderPath '\inbox\Retention Folder'

Leaves me this error:
 {"error":{"code":"RequestBodyRead","message":"The property 'PropertyId' does not exist on type
                          'microsoft.graph.singleValueLegacyExtendedProperty'. Make sure to only use property names that are defined by the type or mark the type as open type."}}

No matter what folder I run it on.  I obtained the policytagvalue by running this command:
get-EXRFolderfrompath -MailboxName $mailbox.userprincipalname -FolderPath '\inbox\Retention Folder' -PropList (Get-EXRItemRetentionTags)

amd then converted the value it returned in base64 into the full GUID.

**Comment by gscales** [comment]
fixed in version 3.50.0 issue was related to older property format
