### ISSUE TITLE
Get Messages

### ISSUE THREAD

**Issue by elijahgagne** [gscales/Exch-Rest#5]
I'd like to look into adding some messaging support (https://msdn.microsoft.com/en-us/office/office365/api/mail-rest-operations#GetMessages). Currently I'm thinking it would make sense to create a Get-Message function.

**Comment by gscales** [comment]
So there are currently a number of Item enumeration cmdlets

Get-FocusedInboxItems
Get-FolderItems
Get-InboxItems
Get-CalendarItems

These will essentially enumerate every item in a particular folder and return a minimal set of properties these may help as a base for what you want to do.

**Comment by elijahgagne** [comment]
Thanks for your continued work on this module. At some point I'd like to contribute some useful code to it, but I don't see that happening right now and I don't see a reason to keep this item open so I'm going to close it.
