### ISSUE TITLE
Example 4 and 4a doesn´t support federated account login

### ISSUE THREAD

**Issue by DanijelkMSFT** [gscales/Exch-Rest#8]
Hi Glen,
I was trying to use your module with Example 4/4a with federated accounts but it´s failing.
I thinks that because of the redirection to the federation server...
Any chance to get working somehow?
Thanks,
Danijel

**Comment by gscales** [comment]
Thanks Danijel

Currently the module doesn't support WS-Federation so authentication won't work, its not really an easy fix for this I'll take it up and address it partially in the next version by allowing an import of the Token from the ADAL library. Long term I'd like to support WS-Federation but it requires some more complex coding and time to resolve

**Comment by DanijelkMSFT** [comment]
cool, ADAL library support would be great :-) also exploring this options at the moment...
another small feedback the examples 4 and 4a are including -redirectUrl as parameter but the functions not, not sure if it´s something missing in function or just the old story of copy&paste...
